# Generated by Django 4.2.4 on 2023-09-10 00:57

import api.models
import api.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("description", models.TextField(max_length=360)),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        default=api.models.default_icon_image,
                        null=True,
                        upload_to=api.models.movie_icon_upload_path,
                        validators=[api.validators.validate_image_file_extension],
                    ),
                ),
                (
                    "banner_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.movie_banner_upload_path,
                        validators=[api.validators.validate_image_file_extension],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stars",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.movie"
                    ),
                ),
            ],
        ),
    ]
