# Generated by Django 4.2.4 on 2023-09-03 11:48

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rating_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="icon",
            field=models.FileField(
                blank=True, null=True, upload_to=api.models.movie_icon_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.movie"
            ),
        ),
    ]
