# Generated by Django 4.2.4 on 2023-09-03 21:53

import api.models
import api.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_movie_icon_alter_rating_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="banner_img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.models.movie_banner_upload_path,
                validators=[api.validators.validate_image_file_extension],
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="icon",
            field=models.FileField(
                blank=True,
                default=api.models.default_icon_image,
                null=True,
                upload_to=api.models.movie_icon_upload_path,
                validators=[
                    api.validators.validate_icon_image_size,
                    api.validators.validate_image_file_extension,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.movie"
            ),
        ),
    ]
