# Generated by Django 4.2.4 on 2023-09-05 02:38

import api.models
import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movie_banner_img_alter_movie_icon_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='icon',
            field=models.FileField(blank=True, default=api.models.default_icon_image, null=True, upload_to=api.models.movie_icon_upload_path, validators=[api.validators.validate_image_file_extension]),
        ),
    ]
